
# Instalacion librerias ----

install.packages("googlePolylines")
install.packages("paletteer")
install.packages("ecmwfr")
install.packages("ncdf4")
install.packages("maps")
install.packages("mapdata")
install.packages("maptools")
install.packages("rgdal")
install.packages("gdalUtilities")
install.packages("spatstat")
install.packages("MODIStsp")
install.packages("ggmap")
install.packages("lubridate")
install.packages("rgeos")
install.packages("reshape2")
install.packages("lmtest")
install.packages("tm")
install.packages("csv")
install.packages("lmtest")
install.packages("csvread")
install.packages("caret")
install.packages("openair")
install.packages("gridExtra")
install.packages("printr")
install.packages("corrplot")
install.packages("randomForest")
install.packages("tdr")
install.packages("tidyverse")
install.packages("ggExtra")
install.packages("ggmap")
install.packages("ggpubr")
install.packages("readr")
install.packages("httr")
install.packages("ggmap")
install.packages("gepaf")#!!!
install.packages("lubridate")
install.packages("foreach")
install.packages("xgboost")
install.packages("Metrics")       # rmse, mae, etc.
install.packages("tidyr")
install.packages("broom")